export const searchKeywords = {
  migrationtools: [
    'import',
    'export',
    'migrate',
    'substack',
    'substack',
    'migration',
    'medium',
    'wordpress',
    'wp',
    'squarespace',
    'beehiiv',
  ],
  codeInjection: ['advanced', 'code injection', 'head', 'footer'],
  labs: [
    'advanced',
    'labs',
    'alpha',
    'private',
    'beta',
    'flag',
    'routes',
    'redirect',
    'translation',
    'editor',
    'portal',
  ],
  history: ['advanced', 'history', 'log', 'events', 'user events', 'staff', 'audit', 'action'],
  dangerzone: [
    'danger zone',
    'delete all content',
    'delete site',
    'reset all authentication',
    'reset api keys',
    'reset password',
    'compromised credentials',
    'lock staff users',
    'sign out all staff',
  ],
};
