export const searchKeywords = {
  titleAndDescription: [
    'general',
    'title and description',
    'site title',
    'site description',
    'title & description',
  ],
  timeZone: ['general', 'time', 'date', 'site timezone', 'time zone'],
  publicationLanguage: ['general', 'publication language', 'locale'],
  siteAccess: ['general', 'site access', 'private', 'password', 'access code', 'visibility'],
  metadata: [
    'general',
    'metadata',
    'title',
    'description',
    'search',
    'engine',
    'google',
    'meta data',
    'twitter card',
    'structured data',
    'rich cards',
    'x card',
    'social',
    'facebook card',
    'llms',
    'ai',
    'ai search engines',
    'llm',
  ],
  socialAccounts: [
    'general',
    'social accounts',
    'facebook',
    'twitter',
    'threads',
    'bluesky',
    'mastodon',
    'tiktok',
    'youtube',
    'instagram',
    'linkedin',
    'structured data',
    'rich cards',
  ],
};
